### ISSUE TITLE
โปรแกรมร้านไก่ดูดวง

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/ChickenHoro#10]

**Comment by Maimeetang** [comment]
https://replit.com/@Maimeetang/project

**Comment by Phummyphum** [comment]
https://www.canva.com/design/DAFdXEVb5Aw/SIV2lGOt9ZQYVwa135U4wg/view?utm_content=DAFdXEVb5Aw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
สไลด์นำเสนอ
