### ISSUE TITLE
เซียมซี

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/ChickenHoro#3]
เราจะให้ผู้ใช้กดปุ่มเขย่าให้เซียมซีตกลงมา เพื่อทำนาย โดยการเขย่าจะเป็นอัตราสุ่มเพื่อให้เหมือนในชีวิตจริง

**Comment by Maimeetang** [comment]
![image](https://user-images.githubusercontent.com/110970005/221362499-2b50297c-252f-4f3a-a935-fd5ed025b40d.png)
![image](https://user-images.githubusercontent.com/110970005/221362598-c0f8f84c-9597-4aaa-9772-f43285e11a07.png)
![image](https://user-images.githubusercontent.com/110970005/221362605-97a83f29-82de-4584-97b1-901d0afdac23.png)
ออกแบบและเขียนโปรแกรมคร่าวๆสำเร็จแล้ว เกิดปัญหาเรื่องฟอนต์ภาษาไทยใน terminal

**Comment by Maimeetang** [comment]
เว็บอ้างอิง https://www.watsons.co.th/store-chi-chi-1-18
