### ISSUE TITLE
ราศรี 

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/ChickenHoro#4]
ให้กรอกราศรีเพื่อที่จะดูดวงชะตาของราศรีนั้นๆ

**Comment by CHICKIINY** [comment]
https://youtu.be/GLfN3z9SeVQ
แก้ปัญหา cout เป็นภาษาไทยไม่ได้

**Comment by CHICKIINY** [comment]
เว็บอ้างอิงข้อมูลการดูดวงจากราศี
https://www.sanook.com/horoscope/myhoro/monthly/

**Comment by CHICKIINY** [comment]
![Screenshot (315)](https://user-images.githubusercontent.com/110966137/221421685-3a8540cb-7a4a-4062-8582-a5e45552c6c4.png)
![Screenshot (316)](https://user-images.githubusercontent.com/110966137/221421690-c6415966-6a10-4cef-852c-f067e145a779.png)
ได้เริ่มเขียน functions และกำหนดตัวเลือกทั้ง 12 เดือน

**Comment by CHICKIINY** [comment]
![Screenshot (317)](https://user-images.githubusercontent.com/110966137/221421925-b54b58ab-ee3e-4e3c-a603-dade1c6319b3.png)
เพิ่มข้อมูลทั้ง 12 เดือน และจัดรูปให้อ่านง่าย

**Comment by CHICKIINY** [comment]
![Screenshot (320)](https://user-images.githubusercontent.com/110966137/222755603-6a1741ce-d8ff-4abf-ac9b-9648b3b14fdc.png)
ตัวอย่างการแสดงผล ใน Terminal

**Comment by CHICKIINY** [comment]
[3.txt](https://github.com/Phummyphum/ChickenHoro/files/10901916/3.txt)
[4.txt](https://github.com/Phummyphum/ChickenHoro/files/10901917/4.txt)
[5.txt](https://github.com/Phummyphum/ChickenHoro/files/10901918/5.txt)
[6.txt](https://github.com/Phummyphum/ChickenHoro/files/10901919/6.txt)
[7.txt](https://github.com/Phummyphum/ChickenHoro/files/10901921/7.txt)
[8.txt](https://github.com/Phummyphum/ChickenHoro/files/10901923/8.txt)
[9.txt](https://github.com/Phummyphum/ChickenHoro/files/10901924/9.txt)
[10.txt](https://github.com/Phummyphum/ChickenHoro/files/10901925/10.txt)
[11.txt](https://github.com/Phummyphum/ChickenHoro/files/10901926/11.txt)
[12.txt](https://github.com/Phummyphum/ChickenHoro/files/10901927/12.txt)
[1.txt](https://github.com/Phummyphum/ChickenHoro/files/10901928/1.txt)
[2.txt](https://github.com/Phummyphum/ChickenHoro/files/10901929/2.txt)
[Zodiac.txt](https://github.com/Phummyphum/ChickenHoro/files/10901934/Zodiac.txt)

**Comment by CHICKIINY** [comment]
#include <iostream>
#include <string>
#include <fstream>
#include <iomanip>

using namespace std;

void showzodiac();
int picknumber();
void zodiachoro();
void endhoro();

int main()
{
    showzodiac();
    picknumber();
    zodiachoro();
    endhoro();

    return 0;
}

void showzodiac()
{
    int i;
    string textline;
    cout << "ดูดวง กับ 12 ราศี" << endl;
    cout << "------------------------------\n";
    ifstream source("Zodiac.txt");
    for(i = 1;i <= 12;i++)
    {
        getline(source, textline);
        cout << setw(2) << i << ". " << textline << endl;
    }
    source.close();
    cout << "------------------------------\n";
}

int picknumber()
{
    int p;
    cout << "เลือกราศีของคุณ : ";
    cin >> p;
    cout << "------------------------------\n";
    return p;
}

void zodiachoro()
{
    int p;
    if(p == 1)
    {
        string textline;
        ifstream source("1.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();
    }
    else if(p == 2)
    {
        string textline;
        ifstream source("2.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();
    }
    else if(p == 3)
    {
        string textline;
        ifstream source("3.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();   
    }
    else if(p == 4)
    {
        string textline;
        ifstream source("4.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();        
    }
    else if(p == 5)
    {
        string textline;
        ifstream source("5.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();    
    }
    else if(p == 6)
    {
        string textline;
        ifstream source("6.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 7)
    {
        string textline;
        ifstream source("7.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();
    }
    else if(p == 8)
    {
        string textline;
        ifstream source("8.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 9)
    {
        string textline;
        ifstream source("9.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();        
    }
    else if(p == 10)
    {
        string textline;
        ifstream source("10.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 11)
    {
        string textline;
        ifstream source("11.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 12)
    {
        string textline;
        ifstream source("12.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();        
    }
    else
    {
        cout << "เลือกตัวเลขระหว่าง 1-12\n";
    }


}

void endhoro()
{
    cout << "------------------------------\n";
}

**Comment by CHICKIINY** [comment]
#include <iostream>
#include <string>
#include <fstream>
#include <iomanip>

using namespace std;

void showzodiac(); //แสดงราศีทั้ง 12 โดยดึงข้อมูลจากไฟล์ Zodiac.txt 
int picknumber(); //เก็บข้อมูลจากผู้ใช้
void zodiachoro(); //นำข้อมูลที่เก็บจากผู้ใช้ เพื่อมาดึงข้อมูลจากไฟล์ 1-12 และแสดงผล 
void endhoro(); //จบโปรแกรม

int main() //เรียกใช้ฟังก์ชั่น
{
    showzodiac(); 
    picknumber();
    zodiachoro();
    endhoro();

    return 0; 
}

void showzodiac() //แสดงราศีทั้ง 12 โดยดึงข้อมูลจากไฟล์ Zodiac.txt 
{
    int i; 
    string textline; 
    cout << "ดูดวง กับ 12 ราศี" << endl;
    cout << "------------------------------\n";
    ifstream source("Zodiac.txt"); //เปิดไฟล์ Zodiac.txt
    for(i = 1;i <= 12;i++) //วนให้ครบ 12 ราศี
    {
        getline(source, textline); 
        cout << setw(2) << i << ". " << textline << endl; //จัดเลขนำหน้าให้ตรงกัน
    }
    source.close(); //ปิดไฟล์ Zodiac.txt
    cout << "------------------------------\n";
}

int picknumber() //เก็บข้อมูลจากผู้ใช้
{
    int p; //ประกาศตัวแปร p
    cout << "เลือกราศีของคุณ : "; 
    cin >> p; //เก็บราศีของผู้ฝช้ไว้ใน p
    cout << "------------------------------\n";
    return p;
}

void zodiachoro() //นำข้อมูลที่เก็บจากผู้ใช้ เพื่อมาดึงข้อมูลจากไฟล์ 1-12 และแสดงผล 
{
    int p; //ประกาศตัวแปร p
    if(p == 1) //ถ้า p = 1
    {
        string textline;
        ifstream source("1.txt"); //เปิดไฟล์ 1.txt
        while(getline(source, textline)) //รันจนครบทุกบรรทัด
        {
            cout << textline << endl; 
        }
        source.close(); //ปิดไฟล์ 1.txt
    }
    else if(p == 2)
    {
        string textline;
        ifstream source("2.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();
    }
    else if(p == 3)
    {
        string textline;
        ifstream source("3.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();   
    }
    else if(p == 4)
    {
        string textline;
        ifstream source("4.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();        
    }
    else if(p == 5)
    {
        string textline;
        ifstream source("5.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();    
    }
    else if(p == 6)
    {
        string textline;
        ifstream source("6.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 7)
    {
        string textline;
        ifstream source("7.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();
    }
    else if(p == 8)
    {
        string textline;
        ifstream source("8.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 9)
    {
        string textline;
        ifstream source("9.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();        
    }
    else if(p == 10)
    {
        string textline;
        ifstream source("10.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 11)
    {
        string textline;
        ifstream source("11.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();       
    }
    else if(p == 12)
    {
        string textline;
        ifstream source("12.txt");
        while(getline(source, textline))
        {
            cout << textline << endl;
        }
        source.close();        
    }
    else
    {
        cout << "เลือกตัวเลขระหว่าง 1-12\n"; //ผู้ใช้ใส่ input ที่ไม่ใช่ 1-12
    }


}

void endhoro() //จบโปรแกรม
{
    cout << "------------------------------\n";
}
