### ISSUE TITLE
เนื้อคู่

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/ChickenHoro#5]
ดูความเข้ากันได้ของเนื้อคู่จากราศรี อาจมีฟังก์ชั่นเพิ่มเติม

**Comment by phuennae** [comment]
อ้างอิงข้อมูลจาก https://horoscope.kapook.com/view255101.html และ https://web.ku.ac.th/schoolnet/snet2/knowledge_math/zodiac.htm

**Comment by phuennae** [comment]
![image](https://user-images.githubusercontent.com/113125472/222392473-bf630f08-de4d-4ae4-810f-ac98f3debdb8.png)

**Comment by phuennae** [comment]
![image](https://user-images.githubusercontent.com/113125472/222392651-52f1245e-074c-430a-ad62-5b49dd5c6e8c.png)
https://cpp.sh/?source=%2F%2F+Example+program%0A%23include+%3Ciostream%3E%0A%23include+%3Cstring%3E%0A%0Aint+main()%0A%7B%0A++std%3A%3Astring+name%3B%0A++std%3A%3Acout+%3C%3C+%22What+is+your+name%3F+%22%3B%0A++getline+(std%3A%3Acin%2C+name)%3B%0A++std%3A%3Acout+%3C%3C+%22Hello%2C+%22+%3C%3C+name+%3C%3C+%22!%5Cn%22%3B%0A%7D

**Comment by phuennae** [comment]
มีการdedign programเสร็จแล้วเหลือแก้ตัวprogramให้เป็นภาษาไทยและคอยดูบัคต่างๆ

**Comment by phuennae** [comment]
![image](https://user-images.githubusercontent.com/113125472/222394583-b01cea80-c1e4-4fd9-a67d-dc5add76669b.png)

**Comment by phuennae** [comment]
![222392651-52f1245e-074c-430a-ad62-5b49dd5c6e8c](https://user-images.githubusercontent.com/113125472/222394722-c4e75553-3a72-42f9-8ff8-7427832e9000.png)

**Comment by phuennae** [comment]
อ้างอิงข้อมูลจาก https://www.sanook.com/horoscope/love/matching/

**Comment by phuennae** [comment]
โปรแกรมใหม่ : https://replit.com/@PhuenpaCHMP/enuuekhuu?fbclid=IwAR3Lv7bdMaf6bMYNah-phzhHvaqSF-u7jRB8602BTKunzd0g_epg4J4Tkxw

**Comment by phuennae** [comment]
![image](https://user-images.githubusercontent.com/113125472/224091590-ce055a5f-ffce-4fb9-935a-52bb14715640.png)

**Comment by phuennae** [comment]
มีการปรับโปรแกรมจากตอนที่ให้ผู้ใช้ได้ใส่ราศีที่ต้องการทราบแล้วตัวโปรแกรมจะแสดงค่าราศีเนื้อคู่ของราศีนั้นๆ เป็นให้ผู้ใช้ใส่ราศี2ราศีที่ต้องการรู้ว่ามีความเข้ากันยังไงและตัวโปรแกรมจะแสดงข้อมูลที่หามาว่า2ราศีนั้นเข้ากันยังไงบ้าง ถ้าคบกันจะเป็นยังไง เสริมดวงกันยังไง อยู่ด้วยกันควรปรับตัวยังไง

**Comment by phuennae** [comment]
ในช่วงแรกที่เปลี่ยนตัวโปรแกรมใหม่ได้เจอปัญหาคือการใส่ราศีไปราศีนึงแล้วตัวโปรแกรมแสดงค่าไม่ตรงกับราศีที่ใส่ไป แต่ได้มีการแก้ไขเป็นที่เรียบร้อยแล้ว

**Comment by phuennae** [comment]
ทั้งนี้อาจมีการปรับเปลี่ยนโปรแกรมอีก อาจจะทำให้อ่านง่ายขึ้นเรียงคำสวยขึ้น
