### ISSUE TITLE
ไพ่ยิปซี

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/ChickenHoro#7]
เป็นการนำไพ่ดูดวงที่เป็นที่นิยมที่สุดมาทำนายดวงให้กับผู้ใข้พร้อมบอกความหมายและแสดงรูปไฟ่โดยใช้ตัวอักษรแสดงผลบนคอนโซล

**Comment by AongNoppolNunpiang** [comment]
เว็บไซต์อ้างอิงในการทำ
1.ไพ่ชุดหลัก https://www.thairath.co.th/horoscope/belief/2179348
                   https://lifestyle.campus-star.com/horoscope/103411.html

2.ไพ่ชุดรอง https://lifestyle.campus-star.com/horoscope/103529.html
                  https://lifestyle.campus-star.com/horoscope/103546.html
อาจมีเพิ่มเติมในภายหลัง

**Comment by AongNoppolNunpiang** [comment]
จากการลองมาในระยะเวลาหนึ่ง เนื่องจากการดูดวงแบบไพ่ยิปซี ค่อยข้างจะเป็นการดูดวงแบบ การทำนายโดยรวม ทำให้จะระบุคำตอบชัดเจนในการดูดวงนั้นๆคนนั้นๆได้ค่อยข้างยาก โดยเขียนเบื้องต้นในตอนนี้คือการให้เลือกเลขมา 5 เลข และจะทำการบอก ลักษณะนิสัยโดยคราวๆของคนนั้นๆ การงาน การเงิน สุภาพ และสิ่งที่ไพ่อยากจะบอกคุณ(คนที่ดู) 
หมายเหตุภายหลังอาจมีการเปลี่ยนแปลงวิธีการ แต่เนื่องจากปกติแล้วการดูดวงโดยไพ่ยิปซี จะเป็นการให้ผู้เลือกหยิบไพ่ออกมาเอง เลยทำแบบนี้
![image](https://user-images.githubusercontent.com/110972175/222550764-832c2818-2b44-4759-8e8d-f278c49a01f6.png)

**Comment by AongNoppolNunpiang** [comment]
แต่ว่าไม่รู้โปรแกรมเป็นอะไรตอนที่พิมเลขสองจะบัคออกมาแบนี้ตลอด
![image](https://user-images.githubusercontent.com/110972175/222551033-37b80666-6813-41e0-a35b-472f114c1542.png)

**Comment by AongNoppolNunpiang** [comment]
> แต่ว่าไม่รู้โปรแกรมเป็นอะไรตอนที่พิมเลขสองจะบัคออกมาแบนี้ตลอด ![image](https://user-images.githubusercontent.com/110972175/222551033-37b80666-6813-41e0-a35b-472f114c1542.png)

แต่ทำในเว็บเลข 2 กับไม่มีปัญหาอะไร
![image](https://user-images.githubusercontent.com/110972175/222551557-1337ffb9-cd00-4c49-a18e-4f753e52a6da.png)

**Comment by AongNoppolNunpiang** [comment]
ที่คิดว่าจะทำต่อไปอาจจะเป็นการแก้คำให้ดูอ่านละเข้าใจง่ายละเหมือนคำทำนายมากขึ้นและถ้าทันจะทำไพ่ชุดเล็กด้วยซึ่งถ้าทำทั้งหมดก็จะมีไพ่ทั้งหมด78ใบนั้นเอง
